developers/limits.md

Adds the limit proposed in [Limit query size to 35kb for all chains](https://www.notion.so/textile/Limit-query-size-to-35kb-for-all-chains-413a991e28904fa6b3c7533d4f023283)
cc @jsign

Add query limit

---

README.md

Also includes some formatting changes

Update readme to remove libp2p stuff

---

README.md
specs/sql/DataTypes.md
specs/sql/Header.md
specs/sql/README.md
specs/sql/StatementTypes.md

Initial move of specs from Notion to GitHub. Fixes #30
Note that this PR contains no real updates beyond minor fixes and nits. Any new spec changes etc should be done as separate PRs against this baseline version.

Migrate notion spec into docs repo

---

README.md
specs/sql/README.md

Missed this in the previous PR. This fixes tables and math so that they render nicely on GitHub.

Use proper gfm + tex math

---

specs/sql/README.md
specs/sql/StatementTypes.md

Specifies deterministic rowid behavior in the spec

---

specs/sql/README.md

Signed-off-by: Carson Farmer <carson.farmer@gmail.com>

Update sql spec readme to latest

---

specs/validator/tableland-openapi-spec.yaml

This PR contains the latest spec discussed in https://github.com/tablelandnetwork/docs/issues/7
Fixes #7

specs/validator: add first version

---

specs/sql/README.md
specs/sql/StatementTypes.md

Document UPSERT syntax

---

specs/sql/DataTypes.md
specs/sql/README.md

Fix: minor typos

---

docs/cli/commands.md

This adds documentation for the work done here: https://github.com/tablelandnetwork/js-tableland-cli/pull/263

[DOCS-30] Add unwrap and extract to CLI docs

---

src/components/Home/HomepageFeatures/index.tsx
src/components/Home/HomepageFeatures/styles.module.css
src/components/Home/index.module.css
src/css/custom.css
src/theme/CodeBlock/Container/styles.module.css
src/theme/CodeBlock/Content/styles.module.css
src/theme/CodeBlock/CopyButton/styles.module.css
src/theme/DocSidebar/Desktop/CollapseButton/styles.module.css
src/theme/Icon/Arrow/index.js
src/theme/SearchBar/styles.css

minor tweaks to match colors, font, style from new website.

color and style tweaks

---

src/components/Home/HomepageFeatures/styles.module.css
src/css/custom.css
src/theme/CodeBlock/Content/styles.module.css
src/theme/DocCard/styles.module.css
src/theme/SearchBar/styles.css

fixes for light theme and a few other nits.

few more style tweaks

---

docusaurus.config.js

Uncomments Fathom in the config file to enable it for site analytics

feat: enable fathom analytics

---

package-lock.json
package.json
src/theme/Root.js

Add a component in Root to track website analytics via Vercel.

feat: add vercel analytics

---

.env.example
docusaurus.config.js
package-lock.json
package.json

Fathom wasn't working for site analytics. This fixes the issue and ensures the script is loaded properly.

fix: change fathom analytics script

---

docs/fundamentals/architecture/limits.md
docs/playbooks/sql/README.md
docs/playbooks/sql/write.md
docs/playbooks/walkthroughs/sql-faqs.md

A few parts of the docs call out the inability to touch multiple tables in a tx. This alters those instances and makes it clear that it _is_ possible.

Adjust verbiage to support multi table txs

---

docs/fundamentals/architecture/table-token.md
vercel.json

I went through all collection pages and updated logo, banner, links, URL, and text to be consistent. This updates the links in the docs.
Also adds a vercel file to silence the vercel bot.

Update table links

---

docs/fundamentals/about/glossary.md

Fixing typos and change some expressions for better understanding

Fixing typos in glossary.md

---

docs/fundamentals/chains/arbitrum.md
docs/fundamentals/chains/ethereum.md

This is a simple PR that adds the Chainstack Sepolia & Goerli faucet to ethereum.md and arbitrum.md

Adds Chainstack faucet to ethereum.md and arbitrum.md

---

docs/api/sdk/classes/Validator.md
docs/api/sdk/namespaces/helpers.md
docs/cli/README.md
docs/cli/chains.md
docs/cli/init.md
docs/contribute/style-guide.md
docs/fundamentals/about/roadmap.md
docs/fundamentals/architecture/table-token.md
docs/playbooks/frameworks/wagmi.md
docs/playbooks/integrations/ipfs.md
docs/quickstarts/chains/arbitrum.md
docs/quickstarts/chains/ethereum.md
docs/quickstarts/chains/filecoin.md
docs/quickstarts/chains/local.md
docs/quickstarts/chains/optimism.md
docs/quickstarts/chains/polygon.md
docs/studio/cli/README.md
docs/validator/node/README.md
package-lock.json
package.json
src/components/SupportedChains.tsx

Adds Optimism Sepolia, removes Optimism Goerli, and makes some component changes to help automate some of the chain content/setup. Note: anything under `docs/api/` is autogenerated.

Add Optimism Sepolia, remove Optimism Goerli

---

docs/sql/faqs.md

Add Mockium, an online CSV/SQL mock data generator, to the list of resources and tools of SQL FAQs.

docs: add data generator to tools
